name: Modify and Push to GitHub Pages Repository

on:
  push:
    branches:
      - "v1.0"

jobs:
  modify-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4

      - name: Run your file modification script
        run: |
          chmod +x ./.github/workflows/modify.sh
          ./.github/workflows/./modify.sh

      - name: Push to target repository
        env:
          TARGET_REPO_TOKEN: ${{ secrets.TARGET_REPO_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]" || exit 1
          git config --global user.email "github-actions[bot]@users.noreply.github.com" || exit 2

          # Setup a temporary folder
          mkdir ../target-repo || exit 3
          cd ../target-repo || exit 4

          # Clone target repository
          git clone https://${TARGET_REPO_TOKEN}@github.com/fvissani-reply/yme-crm-it-pages .git . || exit 5
          
          # Clean the repo and copy everything from the source
          rm -rf * || exit 6
          cp -r ../$(basename $GITHUB_WORKSPACE)/* . || exit 7
          cp -r ../$(basename $GITHUB_WORKSPACE)/.github/assets/* . || exit 8
          rm -rf .github/ || exit 9

          # Commit and push
          git add . || exit 10
          git commit -m "Update from source repo on $GITHUB_SHA" || echo "No changes to commit" || exit 11
          git push origin main || exit 12
